/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.io.*;
import java.util.HashSet;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.Person;

/**
 *
 * @author Administrator
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    Person person;
    public CreateJPanel(Person person) {
        initComponents();
        this.person = person;
        deleteOldPic("src\\image\\");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        txtFax = new javax.swing.JTextField();
        lblFax = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtSsn = new javax.swing.JTextField();
        lblSsn = new javax.swing.JLabel();
        lblBirth = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        txtCity = new javax.swing.JTextField();
        txtBirth = new javax.swing.JTextField();
        lblMedicalRecord = new javax.swing.JLabel();
        lblHealthPlan = new javax.swing.JLabel();
        txtHealthPlan = new javax.swing.JTextField();
        lblBankAccount = new javax.swing.JLabel();
        txtBankAccount = new javax.swing.JTextField();
        lblLicense = new javax.swing.JLabel();
        txtLicense = new javax.swing.JTextField();
        lblLinkedIn = new javax.swing.JLabel();
        txtLinkedIn = new javax.swing.JTextField();
        lblIp = new javax.swing.JLabel();
        txtIp = new javax.swing.JTextField();
        lblNUID = new javax.swing.JLabel();
        txtNUID = new javax.swing.JTextField();
        btnSubmitPhoto = new javax.swing.JButton();
        txtVin = new javax.swing.JTextField();
        lblVin = new javax.swing.JLabel();
        txtUdi = new javax.swing.JTextField();
        lblUdi = new javax.swing.JLabel();
        txtLicensePlate = new javax.swing.JTextField();
        lblLicensePlate = new javax.swing.JLabel();
        txtMedicalRecord = new javax.swing.JTextField();

        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Create Personal Profile");

        lblName.setText("Name:");

        lblCity.setText("City of Residence:");

        lblPhone.setText("Telephone:");

        lblFax.setText("FAX:");

        lblEmail.setText("Email:");

        lblSsn.setText("SSN:");

        lblBirth.setText("Date of Birth(yyyy-mm-dd):");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblMedicalRecord.setText("Medical Record:");

        lblHealthPlan.setText("Health Plan Beneficiary:");

        lblBankAccount.setText("Bank Account Number:");

        lblLicense.setText("License Number:");

        lblLinkedIn.setText("LinkedIn Link:");

        lblIp.setText("Internet Protocol:");

        lblNUID.setText("NUID:");

        btnSubmitPhoto.setText("Submit Photo");
        btnSubmitPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitPhotoActionPerformed(evt);
            }
        });

        lblVin.setText("VIN:");

        lblUdi.setText("UDI:");

        lblLicensePlate.setText("License Plate:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSubmitPhoto)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName)
                            .addComponent(lblBirth)
                            .addComponent(lblCity)
                            .addComponent(lblPhone)
                            .addComponent(lblFax)
                            .addComponent(lblSsn)
                            .addComponent(lblEmail)
                            .addComponent(lblMedicalRecord)
                            .addComponent(lblHealthPlan))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmail)
                            .addComponent(txtSsn)
                            .addComponent(txtPhone)
                            .addComponent(txtFax)
                            .addComponent(txtCity)
                            .addComponent(txtBirth)
                            .addComponent(txtMedicalRecord)
                            .addComponent(txtHealthPlan)
                            .addComponent(txtName))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVin)
                            .addComponent(lblBankAccount)
                            .addComponent(lblLicense)
                            .addComponent(lblLinkedIn)
                            .addComponent(lblIp)
                            .addComponent(lblNUID, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUdi, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLicensePlate, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtVin)
                            .addComponent(txtBankAccount)
                            .addComponent(txtLicense)
                            .addComponent(txtLinkedIn)
                            .addComponent(txtIp)
                            .addComponent(txtNUID)
                            .addComponent(txtUdi)
                            .addComponent(txtLicensePlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblBirth, lblCity, lblEmail, lblFax, lblHealthPlan, lblMedicalRecord, lblName, lblPhone, lblSsn, txtBirth, txtCity, txtEmail, txtFax, txtHealthPlan, txtMedicalRecord, txtPhone, txtSsn});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblBankAccount, lblIp, lblLicense, lblLicensePlate, lblLinkedIn, lblNUID, lblUdi, lblVin, txtBankAccount, txtIp, txtLicense, txtLicensePlate, txtLinkedIn, txtNUID, txtUdi, txtVin});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(lblTitle))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblName)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBirth)
                            .addComponent(txtBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCity)
                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPhone)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFax)
                            .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSsn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSsn))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMedicalRecord)
                            .addComponent(txtMedicalRecord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHealthPlan)
                            .addComponent(txtHealthPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBankAccount)
                            .addComponent(txtBankAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLicense)
                            .addComponent(txtLicense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLinkedIn)
                            .addComponent(txtLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIp)
                            .addComponent(txtIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNUID)
                            .addComponent(txtNUID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVin)
                            .addComponent(txtVin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblLicensePlate)
                                    .addComponent(txtLicensePlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblUdi)
                                    .addComponent(txtUdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSubmitPhoto)
                .addContainerGap(205, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblBirth, lblCity, lblEmail, lblFax, lblHealthPlan, lblMedicalRecord, lblName, lblPhone, lblSsn, txtBirth, txtCity, txtEmail, txtFax, txtHealthPlan, txtMedicalRecord, txtName, txtPhone, txtSsn});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblBankAccount, lblIp, lblLicense, lblLicensePlate, lblLinkedIn, lblNUID, lblUdi, lblVin, txtBankAccount, txtIp, txtLicense, txtLicensePlate, txtLinkedIn, txtNUID, txtUdi, txtVin});

    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:  
        if(txtName.getText().isEmpty()){   
            JOptionPane.showMessageDialog(this, "Please input Name!","Warning", JOptionPane.ERROR_MESSAGE);
            return;
        }else{
            person.setName(txtName.getText());
        }
//          yyyy-mm-dd accepted
        if(txtBirth.getText().matches("(([0-9]{3}[1-9]|[0-9]{2}[1-9][0-9]{1}|[0-9]{1}[1-9][0-9]{2}|[1-9][0-9]{3})-(((0[13578]|1[02])-(0[1-9]|[12][0-9]|3[01]))|((0[469]|11)-(0[1-9]|[12][0-9]|30))|(02-(0[1-9]|[1][0-9]|2[0-8]))))|((([0-9]{2})(0[48]|[2468][048]|[13579][26])|((0[48]|[2468][048]|[3579][26])00))-02-29)")){
            person.setDateOfBirth(txtBirth.getText());
        }else{
            JOptionPane.showMessageDialog(this, "Please input with yyyy-mm-dd!","Warning", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(txtCity.getText().matches("[a-zA-Z]+(?:[\\s-][a-zA-Z]+)*")){   
            person.setCity(txtCity.getText());
        }else{
            JOptionPane.showMessageDialog(this, "Please input City of Residence!","Warning", JOptionPane.ERROR_MESSAGE);
            return;
        }
//          111-222-3333 or 111 222 3333 or (111)222-3333 or (111) 222-3333 or 1111111111 or 1 111-222-3333 accepted      
        if(txtPhone.getText().matches("(1\\s?)?(\\(\\d{3}\\)|\\d{3})\\s?-?\\d{3}-?\\s?\\d{4}")){
            person.setPhone(txtPhone.getText());
        }else{
            JOptionPane.showMessageDialog(this, "Please input correct Phone Number!","Warning", JOptionPane.ERROR_MESSAGE);
            return;
        }
//          +11 222 333 4444 or 111 22 (333) 444 5555 or +1 (222) 333 4444 or 1-222-333 4444 or 11111111111 accepted
        if(txtFax.getText().matches("(\\+?\\d{1,}(\\s?|\\-?)\\d*(\\s?|\\-?)\\(?\\d{2,}\\)?(\\s?|\\-?)\\d{3,}\\s?\\d{3,})")){
            person.setFax(txtFax.getText());
        }else{
            JOptionPane.showMessageDialog(this, "Please input correct FAX Number!","Warning", JOptionPane.ERROR_MESSAGE);
            return;
        }
//          a-zA-Z 0-9 _ - + @ + ** .** .** .** accepted        
        if(txtEmail.getText().matches("([a-zA-Z0-9_\\-\\.]+)@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.)|(([a-zA-Z0-9\\-]+\\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\\]?)")){
            person.setEmail(txtEmail.getText());
        }else{
            JOptionPane.showMessageDialog(this, "Please input correct Email Address!","Warning", JOptionPane.ERROR_MESSAGE);
            return;
        }
//          111-22-3333 accepted (111 cannot be 000 or 666 or 900-999)
        if(txtSsn.getText().matches("(?!000|666)[0-8][0-9]{2}-(?!00)[0-9]{2}-(?!0000)[0-9]{4}")){
            person.setSsn(txtSsn.getText());
        }else{
            JOptionPane.showMessageDialog(this, "Please input correct SSN Number!","Warning", JOptionPane.ERROR_MESSAGE);
            return;
        }
//          M or m + R or r + 12345 or 123456 accepted
        if(txtMedicalRecord.getText().matches("[Mm][Rr]\\d{5,6}")){
            person.setMedicalRecord(txtMedicalRecord.getText());
        }else{
            JOptionPane.showMessageDialog(this, "Please input correct Medical Record Number!","Warning", JOptionPane.ERROR_MESSAGE);
            return;
        }
//          1111-111-1111 or 1111 111 1111 or 1111111111 accepted
        if(txtHealthPlan.getText().matches("\\d{4}\\s?-?\\d{3}-?\\s?\\d{4}")){
            person.setHealthPlan(txtHealthPlan.getText());
        }else{
            JOptionPane.showMessageDialog(this, "Please input correct Health Plan Beneficiary Number!","Warning", JOptionPane.ERROR_MESSAGE);
            return;
        }
//          8 to 17 digits number accepted
        if(txtBankAccount.getText().matches("\\d{8,17}")){
            person.setBankAccount(txtBankAccount.getText());
        }else{
            JOptionPane.showMessageDialog(this, "Please input correct Bank Account!","Warning", JOptionPane.ERROR_MESSAGE);
            return;
        }
//          1Alpha+8Numeric or 9Numeric accepted
        if(txtLicense.getText().matches("[A-Za-z]{1}[0-9]{8,9}")){
            person.setLicense(txtLicense.getText());
        }else{
            JOptionPane.showMessageDialog(this, "Please input correct License Number!","Warning", JOptionPane.ERROR_MESSAGE);
            return;
        }
//          www.linkedin.com/in/accountname accepted   
        if(txtLinkedIn.getText().matches("\\www.linkedin.com/in/\\S*")){
            person.setLinkedIn(txtLinkedIn.getText());
        }else{
            JOptionPane.showMessageDialog(this, "Please input correct LinkedIn Link!","Warning", JOptionPane.ERROR_MESSAGE);
            return;
        }
//          XXX.XXX.XXX.XXX accepted, XXX from 0-255
        if(txtIp.getText().matches("((25[0-5]|2[0-4]\\d|((1\\d{2})|([1-9]?\\d)))\\.){3}(25[0-5]|2[0-4]\\d|((1\\d{2})|([1-9]?\\d)))")){
            person.setIp(txtIp.getText());
        }else{
            JOptionPane.showMessageDialog(this, "Please input correct Internet Protocol Addresses!","Warning", JOptionPane.ERROR_MESSAGE);
            return;
        }
//         any number of 0 + 7 digits number accepted
        if(txtNUID.getText().matches("0*\\d{7}")){
            person.setNuid(txtNUID.getText());
        }else{
            JOptionPane.showMessageDialog(this, "Please input correct NUID!","Warning", JOptionPane.ERROR_MESSAGE);
            return;
        }
//        11 to 17 digits number and letter accepted
        if(txtVin.getText().matches("[a-z0-9]{11,17}")){
            person.setVin(txtVin.getText());
        }else{
            JOptionPane.showMessageDialog(this, "Please input correct Vehicle Identifier Number!","Warning", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if(txtUdi.getText().isEmpty()){   
            JOptionPane.showMessageDialog(this, "Please input correct Unique Device Identifier!","Warning", JOptionPane.ERROR_MESSAGE);
            return;
        }else{
            person.setUid(txtUdi.getText());
        }
        
        if(txtLicensePlate.getText().matches("[a-z0-9]{5,7}")){
            person.setLicensePlate(txtLicensePlate.getText());
        }else{
            JOptionPane.showMessageDialog(this, "Please input correct License Plate!","Warning", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        JOptionPane.showMessageDialog(this, "Profile Infomation Saved"); 
    }//GEN-LAST:event_btnSaveActionPerformed
    
    private void btnSubmitPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitPhotoActionPerformed
        // TODO add your handling code here:
//        make sure only .jpg and .png accepted
        JFileChooser chooser = new JFileChooser();
	FileNameExtensionFilter filter = new FileNameExtensionFilter("jpg","png","JPG","PNG");
	chooser.setFileFilter(filter);
        int showOpenDialog = chooser.showOpenDialog(this);
	if (showOpenDialog == JFileChooser.APPROVE_OPTION) { 
            File addedFile = chooser.getSelectedFile();
            if (addedFile == null) {
                return;
            }
            String fileName =addedFile.getName();
            String prefix=fileName.substring(fileName.lastIndexOf(".")+1);
            if(!(prefix.equals("jpg") || prefix.equals("png") || prefix.equals("JPG") || prefix.equals("PNG"))){
                JOptionPane.showMessageDialog(new JDialog(),"Please choose correct picture");
                return;
            }
            FileInputStream fis = null;
            FileOutputStream fos = null;
            String path = "src\\image\\";
            try {
                //
                File destFile = new File(path,"Personal Picture.png");
                //
                fis = new FileInputStream(addedFile);
                fos = new FileOutputStream(destFile);

                //复制的过程
                byte[] buffer = new byte[5];
                int len;
                while((len = fis.read(buffer)) != -1){
                    fos.write(buffer,0,len);
                }
            } catch (IOException e) {
                e.printStackTrace();
            } finally {
                if(fos != null){
                    //
                    try {
                        fos.close();
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                }
                if(fis != null){
                    try {
                        fis.close();
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                }
            }
            JOptionPane.showMessageDialog(this, "Photo Saved");
	}
    }//GEN-LAST:event_btnSubmitPhotoActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSubmitPhoto;
    private javax.swing.JLabel lblBankAccount;
    private javax.swing.JLabel lblBirth;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFax;
    private javax.swing.JLabel lblHealthPlan;
    private javax.swing.JLabel lblIp;
    private javax.swing.JLabel lblLicense;
    private javax.swing.JLabel lblLicensePlate;
    private javax.swing.JLabel lblLinkedIn;
    private javax.swing.JLabel lblMedicalRecord;
    private javax.swing.JLabel lblNUID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblSsn;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUdi;
    private javax.swing.JLabel lblVin;
    private javax.swing.JTextField txtBankAccount;
    private javax.swing.JTextField txtBirth;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFax;
    private javax.swing.JTextField txtHealthPlan;
    private javax.swing.JTextField txtIp;
    private javax.swing.JTextField txtLicense;
    private javax.swing.JTextField txtLicensePlate;
    private javax.swing.JTextField txtLinkedIn;
    private javax.swing.JTextField txtMedicalRecord;
    private javax.swing.JTextField txtNUID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSsn;
    private javax.swing.JTextField txtUdi;
    private javax.swing.JTextField txtVin;
    // End of variables declaration//GEN-END:variables

//    delete the previous picture submitted
    private void deleteOldPic(String path) {
        File file = new File(path);
	if(!file.exists()){
            return;
	}
	String[] files = file.list();
	for(String fileNames : files){
            File deleteFile = new File(path, fileNames);
            if(deleteFile.isDirectory()){
                deleteOldPic(deleteFile.getAbsolutePath());
		deleteFile.delete();
            }else{
                deleteFile.delete();  
            }
	}
	return;
    }
}
         



